#!/usr/bin/env python3

import os
import sys
import signal
import logging
import logging.handlers
import configparser

from openhd import mavlink as mav


# The first and only argument should be the component config file.
if len(sys.argv) != 2 or not os.path.isfile(sys.argv[1]):
    sys.stderr.write("Usage: " + sys.argv[0] + " <config file>\n")
    exit(1)
config_filename = sys.argv[1]

# Read the config file
config = configparser.ConfigParser()
config['global'] = {
    'log_level': 'critical',
    'syslog_level': 'info',
}
try:
    config.read(config_filename)
except:
    print("Error reading the configuration file: " + config_filename)
    exit

# Configure the logger
log_level = getattr(logging, config['global'].get('log_level').upper())
syslog_level = getattr(logging, config['global'].get('syslog_level').upper())
if not isinstance(log_level, int):
    print("Invalid log level: %s - setting to info" % (args.log_level))
    log_level = logging.INFO
if not isinstance(syslog_level, int):
    print("Invalid syslog level: %s - setting to info" % (args.syslog_level))
    syslog_level = logging.INFO
logger = logging.getLogger('wifi_config')
stream_handler = logging.StreamHandler()
stream_handler.setLevel(log_level)
syslog_handler = logging.handlers.SysLogHandler(address = "/dev/log")
syslog_handler.setLevel(syslog_level)
logging.basicConfig(level=min(log_level, syslog_level), format="%(asctime)s %(levelname)s: %(message)s",
                    datefmt="%H:%M:%S", handlers = [stream_handler, syslog_handler])

handlers = []

# Configure a signal handler to exit cleanly
def handler(signal_received, frame):
    for h in handlers:
        h.terminate()
    router.terminate()

if __name__ == '__main__':

    # Retrieve the configuration parameters
    uart = config['transmitter_telemetry'].get('uart')
    baudrate = int(config['transmitter_telemetry'].get('baudrate'))
    port = int(config['transmitter_telemetry'].get('port'))

    # Setup the exit signal handler
    signal.signal(signal.SIGINT, handler)

    # Create the mavlink router
    router = mav.Router()

    # Create the connection to the transmitter
    logging.debug("Connecting to UART: %s:%d" % (uart, baudrate))
    serial_end = mav.SerialEndpoint(router.get_queue(), uart, baudrate)
    router.add_endpoint(serial_end)
    handlers.append(serial_end)

    # Create the GCS-style connection that the Tx needs
    logging.debug("Creating GCS-type UDP interface on port %d" % (int(port)))
    tx_end = mav.UDPSink(router.get_queue(), port)
    router.add_endpoint(tx_end)
    handlers.append(tx_end)

    router.join()
    exit(0)
