#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

API_KEY=`cat ~/API_KEY`

git submodule update --init

rm -rf debs build


mkdir -p debs/buster

# x64-buster
docker run -v `pwd`:/mnt --rm debian:buster /bin/bash -c "cd /mnt; scripts/mkdeb"
scripts/upload_deb build/*.deb $API_KEY buster testing amd64
mv build/*.deb debs/buster

# armhf-buster
docker run -v /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static -v`pwd`:/mnt --rm arm32v7/debian:buster /bin/bash -c "cd /mnt; scripts/mkdeb"
scripts/upload_deb build/*.deb $API_KEY buster testing armhf
mv build/*.deb debs/buster

# arm64-buster
docker run -v /usr/bin/qemu-aarch64-static:/usr/bin/qemu-aarch64-static -v`pwd`:/mnt --rm arm64v8/debian:buster /bin/bash -c "cd /mnt; scripts/mkdeb"
scripts/upload_deb build/*.deb $API_KEY buster testing arm64
mv build/*.deb debs/buster


mkdir debs/bionic

# x64-bionic
docker run -v `pwd`:/mnt --rm ubuntu:bionic /bin/bash -c "cd /mnt; scripts/mkdeb"
scripts/upload_deb build/*.deb $API_KEY bionic testing amd64
mv build/*.deb debs/bionic

# armhf-bionic
docker run -v /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static -v`pwd`:/mnt --rm arm32v7/ubuntu:bionic /bin/bash -c "cd /mnt; scripts/mkdeb"
scripts/upload_deb build/*.deb $API_KEY bionic testing armhf
mv build/*.deb debs/bionic

# arm64-bionic
docker run -v /usr/bin/qemu-aarch64-static:/usr/bin/qemu-aarch64-static -v`pwd`:/mnt --rm arm64v8/ubuntu:bionic /bin/bash -c "cd /mnt; scripts/mkdeb"
scripts/upload_deb build/*.deb $API_KEY bionic testing arm64
mv build/*.deb debs/bionic


mkdir debs/focal

# x64-focal
docker run -v `pwd`:/mnt --rm ubuntu:focal /bin/bash -c "cd /mnt; scripts/mkdeb"
scripts/upload_deb build/*.deb $API_KEY focal testing amd64
mv build/*.deb debs/focal

# armhf-focal
docker run -v /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static -v`pwd`:/mnt --rm arm32v7/ubuntu:focal /bin/bash -c "cd /mnt; scripts/mkdeb"
scripts/upload_deb build/*.deb $API_KEY focal testing armhf
mv build/*.deb debs/focal

# arm64-focal
docker run -v /usr/bin/qemu-aarch64-static:/usr/bin/qemu-aarch64-static -v`pwd`:/mnt --rm arm64v8/ubuntu:focal /bin/bash -c "cd /mnt; scripts/mkdeb"
scripts/upload_deb build/*.deb $API_KEY focal testing arm64
mv build/*.deb debs/focal
