#!/bin/sh

# Install the OpenHD debian repository
echo "deb https://dl.bintray.com/webbbn/openhd_test buster testing" >> /etc/apt/sources.list
wget -qO - https://bintray.com/user/downloadSubjectPublicKey?username=bintray | apt-key add -

# Install the build dependencies
apt-get update
apt-get install -y git libboost-all-dev cmake build-essential cython3 libv4l-dev libasio-dev wifibroadcast_bridge

# Make sure the submodules are updated
git submodule update --init

# Create the build directory
rm -rf build
mkdir build
cd build

# Build this deb package
cmake ..
make
cpack
