#!/bin/sh

# Default to ground mode
systemctl enable /lib/systemd/system/ground.target
systemctl enable /lib/systemd/system/air.target
systemctl enable /lib/systemd/system/camera.service
systemctl enable /lib/systemd/system/telemetry.service
