#!/bin/sh

DEB=$1
APIKEY=$2
DIST=$3
COMP=$4
ARCH=$5
VER=`cat build/version`

cp ${DEB} .
DEB=`basename ${DEB}`
curl -T ${DEB} -uwebbbn:${APIKEY} "https://api.bintray.com/content/webbbn/openhd_test/Open.HD-NG/${VER}/dists/${DIST}/${COMP}/binary-${ARCH}/${DEB};deb_distribution=${DIST};deb_component=${COMP};deb_architecture=${ARCH}"
rm -f ${DEB}
